apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}{{ .Values.clusterNameSuffix }}-head-lb
spec:
  loadBalancerSourceRanges:
  {{- toYaml .Values.headNodeServiceAllowedRanges | nindent 2 }}
  ports:
  - port: 54399
    protocol: TCP
    targetPort: 54399
    name: metrics
  - port: 10001
    protocol: TCP
    targetPort: 10001
    name: client
  - port: 6379
    protocol: TCP
    targetPort: 6379
    name: redis
  selector:
    ray-node-type: head
    ray-cluster-name: {{ .Release.Name }}{{ .Values.clusterNameSuffix }}
  type: LoadBalancer
